### PR TITLE
Bm snider patch 3

### PR DESCRIPTION
**Pull request by selkind**
## Related issue (if applicable):

Changes proposed in this pull request:
- Setting up project structure for support of multiple file types
- Implemented PathManager
- Refactored TextToString

Capital of Assyria:

### CODE REVIEW

**Comment by selkind** [comment]
I couldn't figure out how to add commits directly to your previous pull request without having permission to push directly to your fork. Please review and let me know what you think. If we're on the same page with this, we can merge this branch and you can create a new pull request for the PDF converter

**Comment by BMSnider** [comment]
Ya, this looks good to me. I will get to work on PDF.

**Comment by selkind** [comment]
Thanks for putting up with my pedanticism. Don't be afraid to push back if you think I'm doing something dumb. Even if I get lucky and turn out to have a good idea, those type of discussions are how we get better at this. Also, don't worry about holding up the pace of development for this project. I'm not aiming for any schedule and won't really be able to make any progress except on weekends.

**Comment by BMSnider** [comment]
Ya, if I see anything I have ideas on I will let you know.

**Pull request merged**
